# -*- coding: utf-8 -*-
"""FOLHA_TCDF.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HGOTC8SWutAv8LKkqOryyM65wVxZPYh5
"""

import pandas as pd
import numpy as np

plan_folha = pd.read_excel('C:\\Users\\willyanmarques\\Tribunal de Contas do Distrito Federal\\General - SECON\\ANO_ATUAL\\FOLHA_DE_PAGAMENTO_2025\\03-MARÇO\\DEMOFIN_TABELA.xlsx', sheet_name='DEMOFIN - T', header=1)
plan_folha.head()

plan_folha['CDG_NAT_DESPESA'] = plan_folha['CDG_NAT_DESPESA'].str.replace('.', '')
plan_folha.head()

plan_rgps = plan_folha.loc[plan_folha['NME_FUNDO'] == 'RGPS', ['CDG_NAT_DESPESA','VALOR_AUXILIAR']]
plan_rgps

proventos_rgps = plan_rgps.loc[plan_rgps['CDG_NAT_DESPESA'].str.startswith('3')]
proventos_rgps

proventos_rgps['CDG_NAT_DESPESA'] = proventos_rgps['CDG_NAT_DESPESA'].str.slice(1)
proventos_rgps

proventos_rgps['CDG_NAT_DESPESA'] = proventos_rgps['CDG_NAT_DESPESA'].replace(['31901101', '31901102', '31901104'], '31901167')
proventos_rgps

proventos_rgps_final = proventos_rgps.groupby('CDG_NAT_DESPESA')['VALOR_AUXILIAR'].sum().reset_index()
proventos_rgps_final
print(proventos_rgps_final)
def preencher_valores(base_path, proventos_rgps_final, output_path):
    # Carregar a planilha base
    base_df = proventos_rgps_final.copy()

    # Garantir que as colunas de referência sejam do mesmo tipo
    base_df['Class. Orçamentãria'] = base_df['Class. Orçamentãria'].astype(str)
    proventos_rgps_final['Class. Orçamentãria'] = proventos_rgps_final['Class. Orçamentãria'].astype(str)

    # Mesclar os dataframes para preencher os valores
    base_df = base_df.merge(proventos_rgps_final[['Class. Orçamentãria', 'Valor']],
                            on='Class. Orçamentãria', how='left')

    # Salvar o resultado
    base_df.to_excel(output_path, index=False)
    print(f"Arquivo salvo em: {output_path}")

# Exemplo de uso
# preencher_valores('base.xlsx', proventos_rgps_final, 'resultado.xlsx')

descontos_rgps = plan_rgps.loc[plan_rgps['CDG_NAT_DESPESA'].str.startswith('2')]
descontos_rgps

descontos_rgps_final = descontos_rgps.groupby(['NME_NAT_DESPESA', 'CDG_NAT_DESPESA'])['VALOR_AUXILIAR'].agg(lambda x: np.sum(np.abs(x)))
descontos_rgps_final